bundler_args: "--without development"
before_script:
  - "cp config/database.example.yml config/database.yml"
  - "cp config/application.example.yml config/application.yml"
  - "cp config/devise.example.yml config/devise.yml" 
  script: "RAILS_ENV=test bundle exec rake spec --trace"
  rvm:
    - 1.9.2
