defaults: &defaults

  # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
  # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
  time_zone: 'Eastern Time (US & Canada)'

  i18n_default_locale: 'en'

  # Configure the default encoding used in templates for Ruby 1.9.
  encoding: 'utf-8'

  # Configure sensitive parameters which will be filtered from the log file.
  filter_parameters:
    - 'password'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
